In [1]:
import numpy as np

In [2]:
def buffer(x: bool):
    return x

def inverter(x: bool):
    return not x

def AND(x: list[bool,...]):
    if len(x)>0:
        return all(x)
    
def NAND(x: list[bool,...]):
    if len(x)>0:
        return not all(x)

def OR(x: list[bool,...]):
    if len(x)>0:
        return any(x)
    
def NOR(x: list[bool,...]):
    if len(x)>0:
        return not any(x)

In [3]:
basics = {
    'BUF': buffer,
    'INV': inverter,
    'AND': AND,
    'NAND': NAND,
    'OR': OR,
    'NOR': NOR,
    # 'INPUT' = INPUT,
    # 'OUTPUT' = OUTPUT
}

In [4]:
class Circuit:
    
    def __init__(self, file):
        self.parse(file)
        
    def parse(self, file):
        with open(file) as f:
            circuit = f.read()
        circuit.replace('  ', ' ')
        self.circuit = {}
        for i, element in enumerate(circuit.split('\n')):
            if element == '':
                continue
            info = element.split(' ')
            if info[0] in ['INPUT', 'OUTPUT']:
                self.circuit.update({info[0]: list(map(int, info[2:]))})
            else:
                self.circuit.update({info[0]+f'_{i}': {'IN': list(map(int, info[1:-1])), 'OUT': int(info[-1])}})
                
        self.length = 0
        for line in circuit.split('\n'):
            for num in line.split(' '):
                try:
                    num = int(num)
                    if num > self.length:
                        self.length = num
                except:
                    continue
        self.length+=2
            
    
    def simulate(self, input_vector):
        self.start = np.asarray([0]*self.length)
        self.next = np.copy(self.start)
        for i, index in zip(input_vector[:], self.circuit['INPUT']):
            self.next[index] = int(i)
        print(self.next[1:])
        while not np.array_equal(self.start, self.next):
            self.start = np.copy(self.next)
            for element in self.circuit.keys():
                if element in ['INPUT', 'OUTPUT']:
                    continue
                self.next[self.circuit[element]['OUT']] = basics[element.split('_')[0]](self.start[self.circuit[element]['IN']])
            # print(self.next[1:])
        print('Output: ', ''.join([str(a) for a in self.next[self.circuit['OUTPUT']][:-1]]))
        return self.next[self.circuit['OUTPUT'][:-1]]

In [5]:
file = 'Circuit Inputs/s27.txt'
c = Circuit(file)

In [6]:
tests = ['1110101', '0001010', '1010101', '0110111', '1010001']
# tests = ['1110101', '0001010']
for test in tests:
    print(test)
    c.simulate(test)

1110101
[1 1 1 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0]
Output:  1001
0001010
[0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0]
Output:  0100
1010101
[1 0 1 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0]
Output:  1001
0110111
[0 1 1 0 0 1 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0]
Output:  0001
1010001
[1 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0]
Output:  1001


In [7]:
file = 'Circuit Inputs/s298f_2.txt'
c = Circuit(file)
# print(c.circuit)

In [8]:
tests = ['10101010101010101', '01011110000000111', '11111000001111000', '11100001110001100', '01111011110000000']
for test in tests:
    print(test)
    c.simulate(test)

10101010101010101
[1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
Output:  00000010101000111000
01011110000000111
[0 1 0 1 1 1 1 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
Output:  00000000011000001000
11111000001111000
[1 1 1 1 1 0 0 0 0 0 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0

In [9]:
file = 'Circuit Inputs/s344f_2.txt'
c = Circuit(file)
# print(c.circuit)

In [10]:
tests = ['101010101010101011111111', 
         '010111100000001110000000', 
         '111110000011110001111111', 
         '111000011100011000000000', 
         '011110111100000001111111']
for test in tests:
    print(test)
    c.simulate(test)

101010101010101011111111
[1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0]
Output:  10101010101010101010101101
010111100000001110000000
[0 1 0 1 1 1 1 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0]
Output:  00011110000000100001111100
111110000011110001111111
[1 1 1 1 1 0 0 0 0 0 1 1 1 1 0 0 0 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0


In [12]:
file = 'Circuit Inputs/s349f_2.txt'
c = Circuit(file)
# print(c.circuit)

In [13]:
tests = ['101010101010101011111111', 
         '010111100000001110000000', 
         '111110000011110001111111', 
         '111000011100011000000000', 
         '011110111100000001111111']
for test in tests:
    print(test)
    c.simulate(test)

101010101010101011111111
[1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0]
Output:  10101010101010101101010101
010111100000001110000000
[0 1 0 1 1 1 1 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0]
Output:  00011110000000101011110000
111110000011110001111111
[1 1 1 1 1 0 0 0 0 0 1 1 1 1 0 0 0 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0